-- ============================================================================
-- ServeStation — Phase 3, Step 6: atomic order creation
-- ----------------------------------------------------------------------------
-- create_order() inserts an order plus its line items and per-line modifiers in
-- a single transaction, so an order can never be persisted with missing items.
-- The app builds the canonical order client-side (ids, money, snapshots via
-- src/domain/orders.ts) and passes it here verbatim; the money CHECK on `orders`
-- still guards `total = subtotal + tax - discount`.
--
-- Orders always enter as `submitted` (carts are never persisted as drafts).
-- Run this in the Supabase SQL Editor after 0001_init.sql.
-- ============================================================================

create or replace function create_order(
  p_order_id          uuid,
  p_store_id          uuid,
  p_order_number      text,
  p_fulfilment_type   fulfilment_type,
  p_customer_name     text,
  p_destination_label text,
  p_note              text,
  p_subtotal          numeric,
  p_tax               numeric,
  p_discount          numeric,
  p_total             numeric,
  p_created_at        timestamptz,
  p_submitted_at      timestamptz,
  p_items             jsonb
)
returns uuid as $$
declare
  v_item      jsonb;
  v_item_id   uuid;
  v_modifier  jsonb;
begin
  insert into orders (
    id, order_number, store_id, fulfilment_type, status,
    customer_name, destination_label, note,
    subtotal, tax, discount, total,
    submitted_at, created_at, updated_at
  ) values (
    p_order_id, p_order_number, p_store_id, p_fulfilment_type, 'submitted',
    p_customer_name, p_destination_label, p_note,
    p_subtotal, p_tax, p_discount, p_total,
    coalesce(p_submitted_at, now()), coalesce(p_created_at, now()), now()
  );

  -- Insert each line item, then its modifier snapshots. Item/modifier ids are
  -- generated by the DB; name/price are snapshots so catalog edits never rewrite
  -- this order.
  for v_item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    insert into order_items (
      order_id, menu_item_id, name_snapshot, unit_price, quantity, note
    ) values (
      p_order_id,
      nullif(v_item->>'menu_item_id', '')::uuid,
      v_item->>'name_snapshot',
      (v_item->>'unit_price')::numeric,
      (v_item->>'quantity')::integer,
      nullif(v_item->>'note', '')
    )
    returning id into v_item_id;

    for v_modifier in
      select * from jsonb_array_elements(coalesce(v_item->'modifiers', '[]'::jsonb))
    loop
      insert into order_item_modifiers (
        order_item_id, modifier_option_id, label, price_delta
      ) values (
        v_item_id,
        nullif(v_modifier->>'modifier_option_id', '')::uuid,
        v_modifier->>'label',
        (v_modifier->>'price_delta')::numeric
      );
    end loop;
  end loop;

  return p_order_id;
end;
$$ language plpgsql;
